build(deps): bump github.com/sigstore/cosign/v2 from 2.4.3 to 2.5.0
Bumps [github.com/sigstore/cosign/v2](https://github.com/sigstore/cosign) from 2.4.3 to 2.5.0.
- [Release notes](https://github.com/sigstore/cosign/releases)
- [Changelog](https://github.com/sigstore/cosign/blob/main/CHANGELOG.md)
- [Commits](https://github.com/sigstore/cosign/compare/v2.4.3...v2.5.0)

---
updated-dependencies:
- dependency-name: github.com/sigstore/cosign/v2
  dependency-version: 2.5.0
  dependency-type: direct:production
  update-type: version-update:semver-minor
...

Signed-off-by: dependabot[bot] <support@github.com>

diff --git a/vendor/gitlab.com/gitlab-org/api/client-go/.gitlab-ci.yml b/vendor/gitlab.com/gitlab-org/api/client-go/.gitlab-ci.yml
--- a/vendor/gitlab.com/gitlab-org/api/client-go/.gitlab-ci.yml
+++ b/vendor/gitlab.com/gitlab-org/api/client-go/.gitlab-ci.yml
@@ -6,10 +6,24 @@ workflow:
     - if: $CI_COMMIT_REF_PROTECTED == "true"
 
 include:
+  - template: Jobs/SAST.gitlab-ci.yml
   - component: ${CI_SERVER_FQDN}/gitlab-org/components/danger-review/danger-review@2.0.0
     inputs:
       job_stage: lint
       job_allow_failure: true
+
+  # NOTE: the two includes below are a hack to conditionally set the tags node
+  # on our Go jobs. We want to use the large Ultimate runners if possible,
+  # which is what we have available in the gitlab-org and gitlab-community (Community Forks)
+  # groups. However, there is no easy way to conditionally set tags or even variables without
+  # jeopardizing existing (complex) workflow:rules or job:rules. Thus, we resort to
+  # this nasty conditionally include hack.
+  - local: '.gitlab/ci/gitlab-go-runner-tags.gitlab-ci.yml'
+    rules:
+      - if: $CI_PROJECT_ROOT_NAMESPACE == 'gitlab-org' || $CI_PROJECT_ROOT_NAMESPACE == 'gitlab-community'
+  - local: '.gitlab/ci/community-go-runner-tags.gitlab-ci.yml'
+    rules:
+      - if: $CI_PROJECT_ROOT_NAMESPACE != 'gitlab-org' && $CI_PROJECT_ROOT_NAMESPACE != 'gitlab-community'
 
 stages:
   - lint
@@ -25,12 +39,15 @@ stages:
         - '1.24'
 
 .go:base:
+  extends:
+    - .go:runner-tags
   # From: https://docs.gitlab.com/ee/ci/caching/#cache-go-dependencies
   variables:
     GOPATH: $CI_PROJECT_DIR/.go
     GOLANGCI_LINT_CACHE: $CI_PROJECT_DIR/.golangci-lint
   before_script:
     - mkdir -p "${GOPATH}" "${GOLANGCI_LINT_CACHE}"
+    - export PATH="${GOPATH}/bin:$PATH"
   cache:
     paths:
       - $GOPATH/pkg/mod/
@@ -38,14 +55,6 @@ stages:
     key:
       files:
         - go.sum
-  # We want to speed up CI a bit.
-  # Community contributors are recommended to use the Community fork
-  # which has access to this runners.
-  # For other forks to free tier namespaces this might fail,
-  # which is a good reminder to use the Community fork and not
-  # to accidentally burn to personal compute minutes.
-  tags:
-    - saas-linux-large-amd64
   # We only need to run Go-related jobs when actual Go files changed
   # or when running either on the default branch or for a tag.
   rules:
@@ -57,6 +66,7 @@ stages:
         - go.mod
         - go.sum
         - .gitlab-ci.yml
+        - .gitlab/ci/*.yml
 
 golangci-lint:
   extends:
@@ -65,7 +75,7 @@ golangci-lint:
   needs: []
   variables:
     REPORT_FILENAME: 'gl-code-quality-report.json'
-  image: golangci/golangci-lint:v1.64.5
+  image: golangci/golangci-lint:v1.64.8
   script:
     - golangci-lint run --print-issued-lines=false --out-format code-climate:$REPORT_FILENAME,line-number
   artifacts:
@@ -73,6 +83,24 @@ golangci-lint:
       codequality: $REPORT_FILENAME
     paths: [$REPORT_FILENAME]
     when: always
+
+verify-generated-code:
+  extends:
+    - .go:base
+  stage: lint
+  needs: []
+  image: golang:1.24-bookworm
+  script:
+    - make generate
+    - |
+      echo "Checking git status"
+      [ -z "$(git status --short)" ] || {
+        echo "Error: Files should have been generated:";
+        git status --short; echo "Diff:";
+        git --no-pager diff HEAD;
+        echo "Run \"make generate\" and try again";
+        exit 1;
+      }
 
 tests:unit:
   extends:
@@ -92,6 +120,8 @@ tests:unit:
     COVERPROFILE_XML_FILENAME: coverage.xml
   script:
     - go run gotest.tools/gotestsum@${GOTESTSUM_VERSION} --format=standard-quiet --junitfile=$JUNIT_FILENAME -- -race -coverprofile=$COVERPROFILE_FILENAME -covermode=atomic ./...
+    - grep -v '_generated.go' "$COVERPROFILE_FILENAME" | grep -v '_mock.go' > "${COVERPROFILE_FILENAME}.tmp"
+    - mv "${COVERPROFILE_FILENAME}.tmp" "$COVERPROFILE_FILENAME"
     - go run github.com/boumenot/gocover-cobertura@${GOCOVER_COBERTURA_VERSION} < $COVERPROFILE_FILENAME > $COVERPROFILE_XML_FILENAME
     - go tool cover -func $COVERPROFILE_FILENAME
   coverage: '/total:.+\(statements\).+\d+\.\d+/'
@@ -109,7 +139,7 @@ tests:unit:
 generate-release-notes:
   stage: deploy
   needs: []
-  image: alpine:3.21.2
+  image: alpine:3.21.3
   before_script:
     - apk add --update jq curl git
   script:
@@ -145,3 +175,11 @@ release:
     tag_message: 'Version $CI_COMMIT_TAG'
     name: '$CI_COMMIT_TAG'
     description: release-notes.md
+
+# Update rules on SAST to ensure the jobs show up in the pipeline
+# this prevents forks that don't have `ultimate` from skipping SAST scans
+# since gitlab-advaced-sast replaces semgrep.
+semgrep-sast:
+  needs: []
+  rules:
+    - when: always
