tree 263b92afcc3089a1a2a5d1a197047d87b1fd6f04 parent c253d1d8cbdf2e881f9d8a36ef5761ccd8355239 author Sascha Grunert <sgrunert@redhat.com> 1643623111 +0100 committer Kubernetes Prow Robot <k8s-ci-robot@users.noreply.github.com> 1643649863 -0800
Update libbpf to v0.6.1

Signed-off-by: Sascha Grunert <sgrunert@redhat.com>

diff --git a/vendor/github.com/aquasecurity/libbpfgo/Makefile b/vendor/github.com/aquasecurity/libbpfgo/Makefile
--- a/vendor/github.com/aquasecurity/libbpfgo/Makefile
+++ b/vendor/github.com/aquasecurity/libbpfgo/Makefile
@@ -75,12 +75,13 @@ libbpfgo-static: $(VMLINUXH) | $(LIBBPF_OBJ)
 		.
 
 libbpfgo-static-test: libbpfgo-test-bpf-static
-	CC=$(CLANG) \
+	sudo env PATH=$(PATH) \
+		CC=$(CLANG) \
 		CGO_CFLAGS=$(CGO_CFLAGS_STATIC) \
 		CGO_LDFLAGS=$(CGO_LDFLAGS_STATIC) \
 		GOOS=linux GOARCH=$(ARCH) \
-		sudo -E -- go test \
-		-tags netgo -ldflags $(CGO_EXTLDFLAGS_STATIC) \
+		go test \
+		-v -tags netgo -ldflags $(CGO_EXTLDFLAGS_STATIC) \
 		.
 
 # vmlinux header file
@@ -94,6 +95,10 @@ $(VMLINUXH): $(OUTPUT)
 		exit 1; \
 	fi
 	@if [ ! -f $(VMLINUXH) ]; then \
+		if [ ! $(BPFTOOL) ]; then \
+			echo "ERROR: could not find bpftool"; \
+			exit 1; \
+		fi; \
 		echo "INFO: generating $(VMLINUXH) from $(BTFFILE)"; \
 		$(BPFTOOL) btf dump file $(BTFFILE) format c > $(VMLINUXH); \
 	fi
